mr-smithers-excellent/docker-build-push

- README.md
- dist/index.js
- src/docker.js
- tests/docker.test.js
- All tags are now lowercase to match [K8s naming conventions](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/)
- Added unit tests
> Make all tags lowercase

- dist/index.js
- src/docker-build-push.js
- tests/docker-build-push.test.js
> Properly set the imageFullName output value

- README.md
- action.yml
- dist/index.js
- src/docker-build-push.js
- src/docker.js
- src/settings.js
- tests/docker-build-push.test.js
- tests/docker.test.js
- Adds support for passing multiple Docker build args
- Update `action.yml` file
- Increase buffer size for larger Docker builds in `child_process.execSync`
Fixes #6
> Add support for Docker build args

- README.md
- action.yml
- dist/index.js
- src/docker.js
- src/settings.js
- tests/docker-build-push.test.js
- tests/docker.test.js
- Add `directory` input parameter for `docker build` commands outside project root
> Add support for custom build directory

- README.md
- dist/index.js
- src/docker.js
- tests/docker.test.js
> Fix Windows ECR docker login command

- README.md
- dist/index.js
- src/docker.js
- tests/docker.test.js
* Updates auto-tagging mechanism to solely use the Git branch name and short SHA
> Update tagging based on branch name

- README.md
- People are lazy, we'll copypasta your examples. v1.0 has been removed, this is the new working version.
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
Co-authored-by: Paul Czarkowski <username.taken@gmail.com>
> Updated the Checkout version

- README.md
- action.yml
- dist/index.js
- package-lock.json
- src/docker-build-push.js
- src/docker.js
- tests/docker-build-push.test.js
- tests/docker.test.js
This references issue https://github.com/mr-smithers-excellent/docker-build-push/issues/22
I went ahead and forked @belon's code and submitted a PR based on it. I'm happy to jump in and make changes as needed, though it may take me a minute. Let me know!
> Ability to push multiple tags

- dist/index.js
- src/docker-build-push.js
> check for empty tag string

- dist/index.js
- src/docker.js
- tests/docker.test.js
> Use whole branch name to determine docker tag

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- README.md
- dist/index.js
- e2e/Dockerfile
- package-lock.json
- package.json
- src/docker-build-push.js
- tests/docker-build-push.test.js
- Fix GitHub Container Registry support to account for new ghcr.io paradigm
- Continue support for legacy docker.pkg.github.com
- Update npm dependencies
- Update docs
- Add e2e tests for GCR, ECR, Docker Hub & GHCR
> Fix GHCR & add e2e tests

- .github/workflows/e2e.yml
- README.md
- package-lock.json
> Upgrade dependencies

- .github/workflows/e2e.yml
- README.md
- action.yml
- dist/index.js
- src/docker-build-push.js
- src/docker.js
- tests/docker-build-push.test.js
- tests/docker.test.js
Adds `addLatest` input param to add `latest` Docker tag for GitOps-generated tags.
> Feature - Add addLatest input

- .github/workflows/e2e.yml
- README.md
- action.yml
- dist/index.js
- src/docker-build-push.js
- src/docker.js
- tests/docker-build-push.test.js
- tests/docker.test.js
* Adds support for `docker build --target` parameter
> Add Docker build target

- .gitignore
- README.md
- action.yml
- dist/index.js
- package-lock.json
- package.json
- src/docker-build-push.js
- src/docker.js
- tests/docker-build-push.test.js
- tests/docker.test.js
Adds a new optional input `addTimestamp` which will append a timestamp to the Docker image tag
Fixes #70
> Add new addTimestamp input

- .github/workflows/e2e.yml
- package-lock.json
- package.json
* Bump npm dependency versions
* Enable contributors to run tests when code owner runs `/ok-to-test` in PR
> Upgrade dependencies & e2e workflow

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/ok-to-test.yml
- .github/workflows/pr.yml
- dist/index.js
- package-lock.json
- package.json
* Adds capability to run e2e tests with `/ok-to-test` command via PR comments
* Removes Code Climate secret from PR workflow
> Add ok-to-test workflow

- .eslintrc
- .github/dependabot.yml
- .github/workflows/e2e.yml
- README.md
- action.yml
- dist/index.js
- src/docker-build-push.js
- src/docker.js
- tests/docker-build-push.test.js
- tests/docker.test.js
- Adds support for multi-platform builds with `multiPlatform` input
- Sets up default `docker-container` driver
- Allows for overriding default Docker driver with input `overrideDriver`
> Adds support for multi-platform builds

- README.md
- action.yml
- src/docker-build-push.js
- tests/docker-build-push.test.js
Adds new `appendMode` boolean input to append custom tags to auto-generated tags instead of overriding them completely.
Closes #336
> feat: add appendMode for tags

- README.md
- dist/index.js
- src/docker-build-push.js
- src/docker.js
Log in the registry even when push is disable to allow registry pulling
> #365 Fixed login issue
